# Copyright (c) Antmicro
# SPDX-License-Identifier: Apache-2.0

from pathlib import Path
from lxml import objectify
from lxml.objectify import ObjectifiedElement
from typing import Any, Optional, Union

from .common import Emitter, ToggleDirection


EMPTY_CHECKSUM = '"000000000"'


class ELEmitter(Emitter):
    def __init__(self, design_dir: Optional[str], *args: Any) -> None:
        super().__init__(*args)
        self.lines: list[str] = ["// Autogenerated. Do not edit"]
        self.reason: str = ""
        self.module_context: Optional[str] = None
        self.instance_context: Optional[str] = None
        self.context_added: bool = False
        self.lineshape: Optional[ObjectifiedElement] = self.read_shape(design_dir, "line")

    def set_reason(self, reason: str) -> None:
        # The " character is illegal, so replace it with '
        self.reason = reason.replace('"', "'")

    def start_module(self, module_name: str, module_path: Optional[str]) -> None:
        self.module_context = module_name
        self.context_added = False

    def end_module(self) -> None:
        self.module_context = None
        self.context_added = False

    def start_instance(self, instance_name: str) -> None:
        self.instance_context = instance_name
        self.context_added = False

    def end_instance(self) -> None:
        self.instance_context = None
        self.context_added = False

    def exclude_fully(self) -> None:
        self.add_reason()
        self.add_context()

    def exclude_line(self, number: int) -> None:
        self.add_context()
        self.add_reason()
        id, content, checksum = self.get_line_context(number)
        self.lines.append(f'Block {id} {checksum} "{content}"')

    def exclude_branch(self, branch: Union[str, int], vector: Optional[int]) -> None:
        self.add_context()
        self.add_reason()
        if vector is not None:
            self.lines.append(f'Branch {branch} {EMPTY_CHECKSUM} "branch{branch}" ({vector}) "vector{vector}"')
        else:
            self.lines.append(f'Branch {branch} {EMPTY_CHECKSUM} "branch{branch}"')

    def exclude_cond(self, cond: Union[str, int], row: Optional[str]) -> None:
        self.add_context()
        self.add_reason()
        if row is not None:
            self.lines.append(f'Condition {cond} {EMPTY_CHECKSUM} "cond{cond} 1 -1" ({row})')
        else:
            self.lines.append(f'Condition {cond} {EMPTY_CHECKSUM} "cond{cond} 1 -1"')

    def exclude_fsm(self, fsm: str, transition: Optional[str]) -> None:
        self.add_context()
        if transition is None:
            self.add_reason()
        self.lines.append(f'Fsm {fsm} {EMPTY_CHECKSUM}')
        if transition is not None:
            self.add_reason()
            self.lines.append(f'Transition {transition}')

    def exclude_assert(self, name: str) -> None:
        self.add_context()
        self.add_reason()
        self.lines.append(f'Assert {name} "assertion"')

    def exclude_toggle(self, name: str, dir: ToggleDirection, bits: Optional[list[Union[int, tuple[int, int]]]]) -> None:
        self.add_context()
        self.add_reason()
        suffix = ""
        if dir == "0->1":
            suffix = " 0to1"
        elif dir == "1->0":
            suffix = " 1to0"

        if bits is None:
            self.lines.append(f'Toggle{suffix} {name} "{name}"')
        else:
            bit_str = "][".join(str(x) if isinstance(x, int) else f"{x[1]}:{x[0]}" for x in bits)
            self.lines.append(f'Toggle{suffix} {name} [{bit_str}] "{name}"')

    def stringify(self) -> str:
        return "\n".join(self.lines) + "\n"

    def add_reason(self):
        self.lines.append(f'ANNOTATION: "{self.reason}"')

    def add_context(self):
        if self.context_added:
            return

        if self.instance_context is not None:
            self.lines.append(f"INSTANCE:{self.instance_context}")
        elif self.module_context is not None:
            self.lines.append(f"MODULE:{self.module_context}")
        else:
            assert False, "Should not be reached!"
        self.context_added = True

    # Returns (id: int, content: str, checksum: str)
    def get_line_context(self, line: int) -> tuple[int, str, str]:
        default_result = (line, f"line{line}", EMPTY_CHECKSUM)

        if self.lineshape is None or self.module_context is None:
            return default_result

        for linedef in self.lineshape.iter("linedef"):
            module_name = str(linedef.attrib["name"])
            try:
                module_name = module_name[:module_name.index("(")].strip()
            except ValueError:
                module_name = module_name.strip()

            if module_name != self.module_context:
                continue

            for linebb in linedef.iter("linebb"):
                first_line = int(linebb.attrib["line_num"])
                last_line = int(linebb.attrib["line_num"])
                for stmt in linebb.iter('linestmt'):
                    first_line = min(first_line, int(stmt.attrib["line_num"]))
                    last_line = max(last_line, int(stmt.attrib["line_num"]))

                if first_line <= line <= last_line:
                    return (
                        int(linebb.attrib["id"]),
                        str(linebb.attrib["bbsig"]),
                        f'"{linebb.attrib["chksum"]}"',
                    )

        return default_result

    def read_shape(self, root: Optional[str], name: str) -> Optional[ObjectifiedElement]:
        try:
            if root is None:
                return None
            content = (Path(root) / f"{name}.verilog.shape.xml").read_bytes()
            return objectify.fromstring(content)
        except:
            return None
